# Generated by Django 6.0.5 on 2026-07-22 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plastic_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('co2_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Customer_app.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seller_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='PlasticAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_product_name', models.CharField(help_text='Name of the harmful plastic item (e.g., Plastic Toothbrush)', max_length=100)),
                ('co2_savings', models.DecimalField(decimal_places=2, help_text='CO2 savings per unit in kg', max_digits=5)),
                ('plastic_savings', models.DecimalField(decimal_places=2, help_text='Plastic saved per unit in kg', max_digits=5)),
                ('reasoning', models.TextField(help_text='AI reasoning explaining why this is better')),
                ('alternative_product', models.ForeignKey(help_text='The green alternative sold on NatureCart', on_delete=django.db.models.deletion.CASCADE, to='Seller_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer')], max_length=10)),
                ('preference', models.CharField(blank=True, choices=[('Zero-Waste', 'Zero Waste Focus'), ('Organic', 'Organic & Natural'), ('Plastic-Free', '100% Plastic Free'), ('Carbon-Footprint', 'Carbon Footprint Minimizer')], max_length=50, null=True)),
                ('total_plastic_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_co2_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_premium_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
