from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Sum, Count
from .models import Product, ProductImage
from Customer_app.models import UserProfile, OrderItem

@login_required
def dashboard(request):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    # Seller metrics
    products = Product.objects.filter(seller=request.user)
    total_products = products.count()
    out_of_stock = products.filter(stock=0).count()
    
    # Calculate orders for products owned by this seller
    order_items = OrderItem.objects.filter(product__seller=request.user)
    total_sales = order_items.count()
    
    # Total revenue generated by selling products
    total_revenue = sum(item.price * item.quantity for item in order_items)
    
    # Collective eco impact made by this seller's products sold
    total_plastic_offset = sum(item.product.plastic_saving_weight * item.quantity for item in order_items if item.product)
    total_co2_offset = sum(item.product.co2_saving_weight * item.quantity for item in order_items if item.product)

    context = {
        "total_products": total_products,
        "out_of_stock": out_of_stock,
        "total_sales": total_sales,
        "total_revenue": total_revenue,
        "total_plastic_offset": total_plastic_offset,
        "total_co2_offset": total_co2_offset,
    }
    
    return render(request, "seller/dashboard.html", context)

@login_required
def add_product(request):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    if request.method == "POST":
        name = request.POST.get("name")
        category = request.POST.get("category")
        description = request.POST.get("description")
        price = request.POST.get("price")
        stock = request.POST.get("stock")
        plastic_saving_weight = request.POST.get("plastic_saving_weight")
        co2_saving_weight = request.POST.get("co2_saving_weight")
        is_premium = request.POST.get("is_premium") == "on"

        product = Product.objects.create(
            seller=request.user,
            name=name,
            category=category,
            description=description,
            price=price,
            stock=stock,
            plastic_saving_weight=plastic_saving_weight,
            co2_saving_weight=co2_saving_weight,
            is_premium=is_premium
        )

        image = request.FILES.get("image")
        if image:
            ProductImage.objects.create(
                product=product,
                image=image
            )

        messages.success(request, f"Product '{name}' added successfully!")
        return redirect("my_products")

    categories = Product.CATEGORY_CHOICES
    return render(request, "seller/add_product.html", {"categories": categories})

@login_required
def my_products(request):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    products = Product.objects.filter(seller=request.user).order_by('-created_at')
    return render(request, "seller/my_products.html", {"products": products})

@login_required
def edit_product(request, id):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    product = get_object_or_404(Product, id=id, seller=request.user)

    if request.method == "POST":
        product.name = request.POST.get("name")
        product.category = request.POST.get("category")
        product.description = request.POST.get("description")
        product.price = request.POST.get("price")
        product.stock = request.POST.get("stock")
        product.plastic_saving_weight = request.POST.get("plastic_saving_weight")
        product.co2_saving_weight = request.POST.get("co2_saving_weight")
        product.is_premium = request.POST.get("is_premium") == "on"
        product.save()

        image = request.FILES.get("image")
        if image:
            # Remove old images
            product.images.all().delete()
            ProductImage.objects.create(
                product=product,
                image=image
            )

        messages.success(request, f"Product '{product.name}' updated successfully.")
        return redirect("my_products")

    categories = Product.CATEGORY_CHOICES
    return render(request, "seller/edit_product.html", {
        "product": product,
        "categories": categories
    })

@login_required
def delete_product(request, id):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    product = get_object_or_404(Product, id=id, seller=request.user)
    product.delete()
    
    messages.success(request, "Product deleted successfully.")
    return redirect("my_products")


@login_required
def manage_orders(request):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    from Customer_app.models import Order
    orders = Order.objects.filter(items__product__seller=request.user).distinct().order_by('-created_at')
    
    orders_data = []
    for order in orders:
        seller_items = order.items.filter(product__seller=request.user)
        seller_total = sum(item.price * item.quantity for item in seller_items)
        orders_data.append({
            'order': order,
            'items': seller_items,
            'seller_total': seller_total,
            'customer_profile': order.customer.userprofile
        })
        
    return render(request, "seller/manage_orders.html", {"orders_data": orders_data})


@login_required
def update_order_status(request, order_id):
    try:
        profile = request.user.userprofile
        if profile.role != "Seller":
            return redirect("home")
    except UserProfile.DoesNotExist:
        return redirect("home")

    from Customer_app.models import Order
    order = get_object_or_404(Order, id=order_id)
    
    # Verify this order actually contains this seller's products
    has_product = order.items.filter(product__seller=request.user).exists()
    if not has_product:
        messages.error(request, "You are not authorized to update this order.")
        return redirect("manage_orders")

    if request.method == "POST":
        status = request.POST.get("status")
        if status in ['Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled']:
            order.status = status
            order.save()
            messages.success(request, f"Order #{order.id} status updated to '{status}'.")
        else:
            messages.error(request, "Invalid status choice.")
            
    return redirect("manage_orders")

