# Generated by Django 6.0.5 on 2026-07-22 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Bags', 'Reusable Bags'), ('Dental', 'Dental Care'), ('Hydration', 'Hydration & Straws'), ('Composting', 'Composting & Kitchen'), ('Cleaning', 'Natural Cleaning'), ('Stationery', 'Seed Paper & Stationery'), ('Home', 'Eco Home & Candles')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('plastic_saving_weight', models.DecimalField(decimal_places=2, help_text='Plastic saved in kg per unit compared to plastic equivalent', max_digits=5)),
                ('co2_saving_weight', models.DecimalField(decimal_places=2, help_text='CO2 saved in kg per unit compared to plastic equivalent', max_digits=5)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Seller_app.product')),
            ],
        ),
    ]
